"""
analyze_note_helpfulness.py — When do 72B notes help vs hurt?

Per-task breakdown from analysis_72b/qa_notes_<task>.csv:

  rescue : Video wrong, V+72B right        → note useful
  break  : Video right, V+72B wrong        → note misleading
  both_right : Video right & V+72B right
  both_wrong : Video wrong & V+72B wrong
  net    : rescue − break (≈ Δ in count of correct answers)

Then for "rescue" vs "break" cases, sample a few each to characterise
what makes a note useful vs misleading. Sample dumped to
`analysis_72b/note_helpfulness_samples.md` for qualitative reading.
"""

import csv
import json
import os
import random
from collections import defaultdict
from pathlib import Path

BASE = Path(__file__).parent
DIR = BASE / "analysis_72b"
OUT_MD = DIR / "note_helpfulness_samples.md"
OUT_CSV = DIR / "note_helpfulness_summary.csv"

TASKS = [
    "materials", "tools", "operation", "quantity",
    "sequence_generation", "sequence_ordering", "step_prediction", "video_verification",
    "experimental_conclusion", "scientific_discovery",
]

# --- 1. per-task summary table ---
rows = []
header = ["task", "n_eval", "rescue", "break", "both_right", "both_wrong",
          "net", "rescue_rate", "break_rate"]
print(f"{'Task':<28}{'n':>6}{'rescue':>8}{'break':>7}{'both_R':>8}{'both_W':>8}{'net':>6}"
      f"{'rescue%':>9}{'break%':>9}")
print("-" * 100)
all_samples = {}  # task -> {"rescue": [...], "break": [...]}
def is_correct(score):
    try:
        return float(score) >= 0.999  # exact-match-only
    except (TypeError, ValueError):
        return False
def is_strictly_wrong(score):
    try:
        return float(score) < 0.001
    except (TypeError, ValueError):
        return True

for task in TASKS:
    csv_path = DIR / f"qa_notes_{task}.csv"
    if not csv_path.exists():
        continue
    rescue, brk, br, bw = 0, 0, 0, 0
    rescues, breaks = [], []
    with open(csv_path) as f:
        for r in csv.DictReader(f):
            sv = r["score_video"]
            sq = r["score_72B"]
            if sv == "" or sq == "":
                continue
            v_ok = is_correct(sv)
            q_ok = is_correct(sq)
            if v_ok and q_ok:
                br += 1
            elif not v_ok and not q_ok:
                bw += 1
            elif not v_ok and q_ok:
                rescue += 1
                rescues.append(r)
            elif v_ok and not q_ok:
                brk += 1
                breaks.append(r)
    n_eval = rescue + brk + br + bw
    if n_eval == 0:
        continue
    net = rescue - brk
    print(f"{task:<28}{n_eval:>6}{rescue:>8}{brk:>7}{br:>8}{bw:>8}{net:>+6}"
          f"{rescue/n_eval*100:>8.1f}%{brk/n_eval*100:>8.1f}%")
    rows.append([task, n_eval, rescue, brk, br, bw, net,
                 f"{rescue/n_eval*100:.2f}", f"{brk/n_eval*100:.2f}"])
    all_samples[task] = {"rescue": rescues, "break": breaks}

with open(OUT_CSV, "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(header)
    w.writerows(rows)
print(f"\n💾 summary → {OUT_CSV}")

# --- 2. qualitative samples ---
random.seed(2026)
N_PER_CATEGORY = 5

def fmt_options(opts_json):
    try:
        opts = json.loads(opts_json)
        if not opts:
            return ""
        return "\n  ".join(f"{k}. {v}" for k, v in sorted(opts.items()))
    except Exception:
        return opts_json

with open(OUT_MD, "w") as f:
    f.write("# Note helpfulness — qualitative samples\n\n")
    f.write("For each task, 5 *rescue* (Video wrong → V+72B right) and 5 *break* "
            "(Video right → V+72B wrong) cases.\n\n")
    f.write("This is generated by `analyze_note_helpfulness.py` from the joined "
            "data in `qa_notes_<task>.csv`.\n\n---\n\n")

    for task in TASKS:
        if task not in all_samples:
            continue
        f.write(f"## {task}\n\n")
        for cat in ("rescue", "break"):
            cases = all_samples[task][cat]
            if not cases:
                f.write(f"### {cat.upper()} (n=0)\n\n")
                continue
            sample = random.sample(cases, min(N_PER_CATEGORY, len(cases)))
            f.write(f"### {cat.upper()} (n={len(cases)})\n\n")
            for c in sample:
                opts = fmt_options(c["options"])
                # truncate notes to keep readable
                note_72 = c["note_72B"]
                f.write(f"**video** `{c['video_path']}` | **question** {c['question']!r}\n\n")
                if opts:
                    f.write(f"  {opts}\n\n")
                f.write(f"  gold = {c['gold']}, "
                        f"pred_video = {c['pred_video']!r} (score {c['score_video']}), "
                        f"pred_72B = {c['pred_72B_note']!r} (score {c['score_72B']})\n\n")
                f.write(f"  **72B note**:\n\n```\n{note_72[:1500]}\n```\n\n")
                f.write("---\n\n")
        f.write("\n")
print(f"💾 samples  → {OUT_MD}")
