#!/usr/bin/env bash
# Wait for v3 training (DDP), then:
#   Phase A: v3 noter inference + eval + push final paper-1 comparison
#   Phase B: pilot the 50-sample InternVL3-78B oracle validation gate
#            (Item 4a of PAPER1_EXTENSION_PLAN.md — decide whether to swap oracle)

set -u
cd "$(dirname "$0")"

PY=/home/yz0392@unt.ad.unt.edu/miniconda3/envs/crag/bin/python
LOG=logs/orchestrate_v3.log
mkdir -p logs

log() { echo "[$(date +%H:%M:%S)] $*" | tee -a $LOG; }

# ---------- Wait for v3 training ----------
log "waiting for v3 DDP training (train_notetaker_vl_v3.py via torchrun) to finish"
while pgrep -fc 'train_notetaker_vl_v3.py' > /dev/null; do
    sleep 120
done
CKPT=checkpoints/notetaker_vl_lora_v3/final
if [ ! -f "$CKPT/adapter_model.safetensors" ]; then
    log "ERROR: expected v3 checkpoint not found at $CKPT"
    ls -la checkpoints/notetaker_vl_lora_v3/ 2>/dev/null | tee -a $LOG
    exit 1
fi
log "v3 checkpoint ready at $CKPT"

# ---------- Phase A.1: v3 inference on test split (8 GPU work-stealing) ----------
log "Phase A.1: v3 inference on v2_split_test.jsonl"
PIDS=()
for gpu in 0 1 2 3 4 5 6 7; do
    nohup env CUDA_VISIBLE_DEVICES=$gpu $PY \
        generate_notes_with_vl_lora_v3.py \
        --lora_path "$CKPT" \
        --test_jsonl train_data/v2_split_test.jsonl \
        > logs/gen_v3_gpu${gpu}.log 2>&1 &
    PIDS+=($!)
done
log "  launched 8 v3 inference jobs (PIDs: ${PIDS[*]})"
for pid in "${PIDS[@]}"; do wait $pid 2>/dev/null; done

N_NOTES=$(find results_v2_split/v3_noter_notes -name "*.json" 2>/dev/null | wc -l)
log "  v3 notes generated: $N_NOTES"

# ---------- Phase A.2: v3 eval with task-aware scorer (8 GPU chunks) ----------
log "Phase A.2: v3 eval on ExpVid test split (Qwen-7B answer)"
EVAL_OUT=results_v2_split/v3_noter_eval

# Re-use evaluate_v2_test_split_fixed.py but override V2_NOTES_DIR
# Quick approach: copy v3 notes to a path the existing eval script reads
mkdir -p $EVAL_OUT
cp -r results_v2_split/v3_noter_notes/* $EVAL_OUT/notes_link/ 2>/dev/null || true

# Cleaner: small Python shim to re-run the eval with v3_noter_notes
$PY << 'PYEOF' > logs/eval_v3_full.log 2>&1
import sys, os
sys.path.insert(0, '.')
# Patch the V2_NOTES_DIR before importing the eval module
os.environ["V2_NOTES_DIR_OVERRIDE"] = "results_v2_split/v3_noter_notes"
os.environ["EVAL_OUT_OVERRIDE"] = "results_v2_split/v3_noter_eval"
# Run inline -- delegate to evaluate_v2_test_split_fixed in 8 chunks per GPU
import subprocess
procs = []
for chunk in range(8):
    env = os.environ.copy()
    env["CUDA_VISIBLE_DEVICES"] = str(chunk)
    p = subprocess.Popen(
        ["python", "evaluate_v3_test_split.py",
         "--benchmark", "expvid",
         "--chunk_id", str(chunk), "--num_chunks", "8"],
        env=env, stdout=open(f"logs/eval_v3_gpu{chunk}.log","w"), stderr=subprocess.STDOUT,
    )
    procs.append(p)
for p in procs: p.wait()
PYEOF
log "  v3 eval done"

# ---------- Phase A.3: aggregate + build final comparison + push ----------
log "Phase A.3: aggregate + push final paper-1 comparison"
$PY compute_per_task_results_v3.py 2>&1 | tee -a $LOG

git add results_v2_split/v3_noter_notes results_v2_split/v3_noter_eval \
        PER_TASK_RESULTS.md NON_MC_REGRESSION_DEEP_DIVE.md 2>/dev/null
git commit -m "v3 task-aware noter — final paper-1 results

Generated by orchestrate_v3_then_extension.sh after v3 DDP training finished.
v3 vs Video / V+v2 / V+v2-promptv2 / task-gated v2 / 72B-oracle final table
in PER_TASK_RESULTS.md.

Co-Authored-By: Claude Opus 4.7 (1M context) <noreply@anthropic.com>" 2>/dev/null
git pull --rebase origin main 2>&1 | tail -3 | tee -a $LOG
git push origin main 2>&1 | tail -3 | tee -a $LOG
log "Phase A complete."

# ---------- Phase B: extension plan immediate actions ----------
# Per PAPER1_EXTENSION_PLAN.md "Immediate next actions":
# Action #3: setup InternVL3-78B on 8× H200, validate vLLM TP=4 fits
# Action #4: 50-sample InternVL3-78B oracle quality check
log "Phase B: 50-sample InternVL3-78B oracle validation (extension plan item 4a)"
# (script + smoke launch — full validation iterates after smoke check)
$PY -c "
print('Phase B will be launched once script validate_oracle_quality.py is in place.')
print('Per plan: pick 50 random items where Qwen2.5-VL-72B oracle exists,')
print('regenerate with InternVL3-78B vLLM TP=4 + task-aware oracle prompts,')
print('side-by-side compare specificity / parseability / correctness.')
" | tee -a $LOG

log "DONE. See $LOG for full trace."
