"""translate_self_notes_scivb.py — translate SciVB self-notes from the
scivideobench_exp cache (md5(video_id)[:16] keyed) into the sample_id-keyed
format that evaluate_v4_test_split.py expects.

Source notes were generated by Qwen2.5-VL-3B (paper-1 baseline self-note);
each note maps to ONE video. SciVB items reuse the same video across multiple
question_ids, so one note maps to many sample_ids.

Source: scivideobench_exp/results_scivideobench/notes_cache/<md5(video_id)>.json
Target: results_v4_split/selfnote_qwen3b_scivb_notes/scivideobench/<md5(sample_id)>.json
"""
import hashlib, json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
TEST_JSONL = ROOT / "train_data" / "v4_split_test.jsonl"
SRC = ROOT / "scivideobench_exp" / "results_scivideobench" / "notes_cache"
DST = ROOT / "results_v4_split" / "selfnote_qwen3b_scivb_notes" / "scivideobench"
DST.mkdir(parents=True, exist_ok=True)


def main():
    items = [json.loads(l) for l in open(TEST_JSONL)]
    scivb = [it for it in items if it.get("benchmark") == "scivideobench"]
    print(f"scivb test items: {len(scivb)}")
    n_written = n_missing = 0
    for it in scivb:
        # video_path is like "scivb_video_id:58827" -> video_id "58827"
        vp = str(it.get("video_path", ""))
        vid = vp.split(":")[-1] if ":" in vp else vp
        src_safe = hashlib.md5(vid.encode()).hexdigest()[:16] + ".json"
        src_p = SRC / src_safe
        if not src_p.exists():
            n_missing += 1
            continue
        try:
            note = json.load(open(src_p)).get("note")
        except Exception:
            n_missing += 1
            continue
        if not note:
            n_missing += 1
            continue
        sid = it["sample_id"]
        out_safe = hashlib.md5(sid.encode()).hexdigest()[:16] + ".json"
        json.dump({"sample_id": sid, "benchmark": "scivideobench", "task": "mc",
                   "note": note}, open(DST / out_safe, "w"))
        n_written += 1
    print(f"  wrote {n_written}, missing {n_missing} -> {DST.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
