"""V8 Stage 1 real-VLM smoke test.

Picks N sample videos per benchmark, runs Qwen-VL-72B extract_kg,
renders the resulting KGs as markdown to V8_STAGE1_SMOKE.md.

Usage:
    CUDA_VISIBLE_DEVICES=4,5,6,7 python scripts/v8_stage1_smoke.py
"""
from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from evaluate_c0_test_split import extract_frames                      # noqa: E402
from ranker_pipeline.common.video_utils import get_video_duration       # noqa: E402

from protonote.data.loaders import load_test_split, resolve_video_path  # noqa: E402
from protonote.v6.llm_client import QwenVL72BClient                    # noqa: E402
from protonote.v8.stages.stage1_extract import extract_kg              # noqa: E402


def pick_samples(benchmark: str, n: int) -> list[dict]:
    items = load_test_split(benchmark=benchmark, limit=None)
    if len(items) <= n:
        return items
    stride = len(items) // n
    return items[::stride][:n]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n-scivb", type=int, default=1)
    ap.add_argument("--n-expvid", type=int, default=2)
    ap.add_argument("--device", default="auto")
    ap.add_argument("--max-frames", type=int, default=16)
    ap.add_argument("--max-tokens", type=int, default=2048)
    ap.add_argument("--model",
                     default="Qwen/Qwen2.5-VL-72B-Instruct",
                     help="HF model name (e.g. Qwen/Qwen2.5-VL-7B-Instruct)")
    ap.add_argument("--out", type=Path, default=ROOT / "V8_STAGE1_SMOKE.md")
    args = ap.parse_args()

    print(f"loading {args.model} on {args.device}")
    # Bypass the V6 singleton (which would return whichever model loaded
    # first) and create a fresh client per invocation.
    vlm = QwenVL72BClient(model_name=args.model, device=args.device)

    lines: list[str] = [
        f"# V8 Stage 1 smoke test ({args.model.split('/')[-1]})",
        "",
        f"Generated by `scripts/v8_stage1_smoke.py`.",
        f"VLM: {args.model} ({args.max_frames} frames/video,",
        f"max_tokens={args.max_tokens}).",
        "",
        "Each section shows: input video meta → raw KG markdown ",
        "(produced by `KnowledgeGraph.render()` after `extract_kg`).",
        "",
    ]

    sample_count = 0
    for bench, n in (("scivideobench", args.n_scivb),
                          ("expvid", args.n_expvid)):
        items = pick_samples(bench, n)
        for it in items:
            sample_count += 1
            sid = it["sample_id"]
            q = (it.get("question") or "").strip()
            task = it.get("task", "?")
            lines.append(f"## {sample_count}. {sid}")
            lines.append("")
            lines.append(f"- **benchmark**: `{bench}` (task: {task})")
            lines.append(f"- **question**: {q[:300]}")
            vp = resolve_video_path(it)
            if not vp or not Path(vp).exists():
                lines.append("- **status**: ❌ video unavailable")
                lines.append("")
                continue
            try:
                duration = float(get_video_duration(vp) or 60.0)
                frames = extract_frames(vp, max_frames=args.max_frames)
            except Exception as e:
                lines.append(f"- **status**: ❌ frame load failed: {e}")
                lines.append("")
                continue

            lines.append(f"- **frames**: {len(frames)}, duration ≈ "
                            f"{duration:.0f}s")
            print(f"[{sample_count}] {sid} — {len(frames)} frames, "
                    f"running extract_kg…")
            t0 = time.time()
            kg = extract_kg(
                frames, vlm,
                question=q,
                duration_sec=duration,
                max_tokens=args.max_tokens,
            )
            elapsed = time.time() - t0
            print(f"  done in {elapsed:.1f}s: "
                    f"{len(kg.entities)} entities, "
                    f"{len(kg.operations)} operations")

            lines.append(f"- **extract elapsed**: {elapsed:.1f}s")
            lines.append(f"- **KG**: {len(kg.entities)} entities, "
                            f"{len(kg.operations)} operations, "
                            f"{len(kg.stages)} stages")
            lines.append("")
            lines.append("### Rendered KG")
            lines.append("")
            lines.append("```markdown")
            lines.append(kg.render())
            lines.append("```")
            lines.append("")

    args.out.write_text("\n".join(lines))
    print(f"\nWrote {args.out}")


if __name__ == "__main__":
    main()
